apiVersion: apps/v1
kind: Deployment
metadata:
  name: taasselunga-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taasselunga-frontend
  template:
    metadata:
      labels:
        app: taasselunga-frontend
    spec:
      containers:
        - name: frontend
          image: lucaads01/taasselunga-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://localhost:30080"