apiVersion: v1
kind: Service
metadata:
  name: taasselunga-api-gateway
spec:
  type: NodePort
  selector:
    app: taasselunga-api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080