apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: lucaads01/taasselunga-notification-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq:5672"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "db_notifications"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "password"