apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |
    CREATE DATABASE db_inventory;
    CREATE DATABASE db_procurement;
    CREATE DATABASE db_pos;
    CREATE DATABASE db_notifications;