apiVersion: apps/v1
kind: Deployment
metadata:
  name: procurement-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: procurement-service
  template:
    metadata:
      labels:
        app: procurement-service
    spec:
      containers:
        - name: procurement-service
          image: lucaads01/taasselunga-procurement-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"