server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/db_pos
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/taasselunga-4d6e5
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com

inventory:
  service:
    url: http://localhost:8081